[package]
name = "mio-serial"
version = "4.0.0"
authors = ["Zac Berkowitz <zac.berkowitz@gmail.com>"]
description = "A serial port implementation for mio"
license = "MIT"
homepage = "https://github.com/berkowski/mio-serial"
repository = "https://github.com/berkowski/mio-serial"
documentation = "http://docs.rs/mio-serial"
readme = "README.md"
keywords = ["rs232", "serial", "mio"]
categories = ["asynchronous", "hardware-support"]
edition = "2018"

[badges]
appveyor = { repository = "berkowski/mio-serial", service = "github" }
travis-ci = { repository = "berkowski/mio-serial", service = "github" }

[features]
default = []
libudev = ["serialport/libudev"]
os-poll = ["mio/os-poll"]
os-ext = ["mio/os-ext"]

[dependencies.mio]
version = "0.8"
# features = ["os-poll", "os-ext"]

[dependencies.serialport]
version = "4"
default-features = false

[target.'cfg(unix)'.dependencies]
nix = "0.19"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["commapi", "handleapi", "winbase"] }
mio-named-pipes = "0.1.5"

[[example]]
name = "read_serialport"
required-features = ["os-poll", "os-ext"]
[patch.crates-io]
mio = {git = "https://github.com/berkowski/mio", branch="public-iosource"}
